title: Pocket Updater Utility
author:
  name: Matt Pannella
  email: mattpannella@gmail.com
description: A thing for updating your Analogue Pocket and some other stuff

domain: https://mattpannella.github.io
baseurl: "/pocket-updater-utility"
url: https://mattpannella.github.io

theme: Modernist
