title: Pocket Updater Utility
author:
  name: Matt Pannella
  email: mattpannella@gmail.com
description: A thing for updating your Analogue Pocket and some other stuff

domain: https://mattpannella.github.io
baseurl: "/pocket-updater-utility"
url: https://mattpannella.github.io

  # generate social links in footer
  social_links:
    # - { platform: devto,          user_url: "https://dev.to/jekyll" }
    # - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
    # - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
    # - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
    - { platform: github,         user_url: "https://github.com/openfpga-cores-inventory/analogue-pocket" }
    # - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
    # - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
    # - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
    # - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
    # - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
    # - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
    # - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
    # - { platform: telegram,       user_url: "https://t.me/jekyll" }
    - { platform: twitter,        user_url: "https://twitter.com/mpannella" }
    # - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

theme: Modernist
